In [13]:
import numpy as np
from numpy.matlib import repmat

In [9]:
x = np.random.randint(0, 10, (3, 4))
print x

[[2 7 0 6]
 [4 4 0 9]
 [8 3 7 2]]


In [10]:
np.square(x)

array([[ 4, 49,  0, 36],
       [16, 16,  0, 81],
       [64,  9, 49,  4]])

In [11]:
y = x[0]
print y

[2 7 0 6]


In [21]:
repmat(y[:, None], 1, 3)

array([[2, 2, 2],
       [7, 7, 7],
       [0, 0, 0],
       [6, 6, 6]])

In [19]:
y[:, None]

array([[2],
       [7],
       [0],
       [6]])